"""`eval/results/*.csv` into the LaTeX the report reads.

Rule 1 of the repository architecture: no number in the report is typed by
hand. Every figure in the prose is a macro defined here and every table is an
`\\input` of a file written here, both from the evaluation's own CSV output.

The rule holds because an undefined control sequence stops a LaTeX build. A
figure that has not been measured therefore has no macro, and citing it fails
the build instead of reaching the page. `\\newcommand` and not
`\\providecommand` or `\\def`, so a name collision fails the same way rather
than silently keeping one of the two definitions.

Rounding lives in `format_value` and nowhere else, so a number cannot be
reported to three decimals in the text and two in a table.

The corpus census, localisation (E5) and throughput (E6) have schemas and
registries. Recognition and correction do not, and theirs are added when those
evaluations produce their first CSV, because a registry written ahead of the
data is a guess about the data.
"""

import csv
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Mapping, Sequence

_LETTERS_ONLY = re.compile(r"[A-Za-z]+")

_ESCAPES = {
    "\\": "\\textbackslash{}",
    "&": "\\&",
    "%": "\\%",
    "$": "\\$",
    "#": "\\#",
    "_": "\\_",
    "{": "\\{",
    "}": "\\}",
    "~": "\\textasciitilde{}",
    "^": "\\textasciicircum{}",
}

_HEADER = (
    "% Generated by src/amadis_htr/report_macros.py from eval/results/*.csv.\n"
    "% Do not edit: rerun eval/run_all.sh instead.\n"
    "%\n"
    "% Empty until the evaluation that feeds it runs. Citing a figure before it\n"
    "% is measured is an undefined control sequence, which stops the build.\n"
    "% That is the point.\n"
)


class MacroNameError(ValueError):
    """Raised when a macro name is not a legal TeX control sequence."""


@dataclass(frozen=True)
class Macro:
    """One reported figure: where it is read from and how it is rounded.

    `over` names a second column on the same row, and the figure becomes the
    ratio of the two. The results CSVs hold counts, never rates, because a
    count is what the evaluation observed and a rate is a reading of it that
    depends on which denominator is meant. Declaring the denominator here
    keeps both on the page from one measurement: the report says 315 of 317
    and 99.4% without either being typed.
    """

    name: str
    csv: str
    select: Mapping[str, str] = field(default_factory=dict)
    column: str = ""
    fmt: str = "text"
    over: str = ""


def escape(text: str) -> str:
    """Make a string safe to typeset, so a printed title cannot run LaTeX."""
    return "".join(_ESCAPES.get(c, c) for c in text)


def format_value(raw: str, fmt: str) -> str:
    """Render one CSV cell. Every rounding decision in the report is here.

    A percentage that rounds to zero is written `<0.01\\%` rather than
    `0.00\\%`, because a measured non-zero error rate is not a perfect result
    and the report must not claim one.
    """
    if fmt == "text":
        return escape(raw)
    if fmt == "int":
        # Grouped, because a page count reaches five digits and 14111 on the
        # page is a string of digits rather than a number a reader can take in.
        # Grouping is presentation, so it lives here with the rounding.
        return f"{int(float(raw)):,d}"
    if fmt.startswith("num"):
        return f"{float(raw):.{int(fmt[3:])}f}"
    if fmt.startswith("hours"):
        # The CSV records elapsed seconds, because that is what the harness
        # timed. Hours are the unit a reader thinks in, and the conversion is
        # presentation, so it lives here with the rounding rather than as a
        # second column restating the first.
        return f"{float(raw) / 3600:.{int(fmt[5:])}f}"
    if fmt.startswith("pct"):
        places = int(fmt[3:])
        value = float(raw) * 100
        floor = 10.0**-places
        if 0 < value < floor:
            return f"<{floor:.{places}f}\\%"
        return f"{value:.{places}f}\\%"
    raise ValueError(f"unknown format {fmt!r}")


def _check_name(name: str) -> None:
    if not _LETTERS_ONLY.fullmatch(name):
        raise MacroNameError(
            f"{name!r} is not a legal control sequence name. TeX stops a control "
            "sequence at the first non-letter, so a digit or an underscore would "
            "put the rest of the name on the page instead of raising an error."
        )


def _select(path: Path, criteria: Mapping[str, str]) -> dict[str, str]:
    with open(path, encoding="utf-8", newline="") as handle:
        rows = [
            row
            for row in csv.DictReader(handle)
            if all(row[key] == value for key, value in criteria.items())
        ]
    if not rows:
        raise KeyError(
            f"{path.name}: no row matches {criteria!r}. The evaluation that "
            "writes this file did not produce the band the report cites."
        )
    if len(rows) > 1:
        raise ValueError(
            f"{path.name}: {criteria!r} matches {len(rows)} rows. A macro names "
            "one figure, so the selector has to identify one row."
        )
    return rows[0]


def render_macros(macros: Iterable[Macro], results: str | Path) -> str:
    """Render one `\\newcommand` per reported figure."""
    results = Path(results)
    lines: list[str] = []
    seen: set[str] = set()
    for macro in macros:
        _check_name(macro.name)
        if macro.name in seen:
            raise MacroNameError(f"{macro.name!r} is defined twice")
        seen.add(macro.name)
        row = _select(results / macro.csv, macro.select)
        if macro.over:
            denominator = float(row[macro.over])
            if denominator == 0:
                raise ValueError(
                    f"{macro.name}: {macro.over} is zero on the selected row, so "
                    "the rate does not exist. A band with nothing in it has no "
                    "accuracy, and reporting one would invent a denominator."
                )
            raw = str(float(row[macro.column]) / denominator)
        else:
            raw = row[macro.column]
        value = format_value(raw, macro.fmt)
        lines.append(f"\\newcommand{{\\{macro.name}}}{{{value}}}")
    return "\n".join(lines) + "\n"


def render_table(
    *, headers: Sequence[str], aligns: str, rows: Sequence[Sequence[str]]
) -> str:
    """Render a `booktabs` tabular body, cells already formatted.

    No vertical rules and no `\\hline`, which is what `booktabs` is for. The
    caller wraps this in whatever float and caption the report wants, so the
    same table can be a figure in the report and a slide in the deck.
    """
    if len(aligns) != len(headers):
        raise ValueError(
            f"{len(headers)} headers against {len(aligns)} alignment letters"
        )
    for row in rows:
        if len(row) != len(headers):
            raise ValueError(
                f"a row has {len(row)} cells but the table has "
                f"{len(headers)} columns"
            )
    body = [
        f"\\begin{{tabular}}{{{aligns}}}",
        "\\toprule",
        " & ".join(headers) + " \\\\",
        "\\midrule",
    ]
    body.extend(" & ".join(row) + " \\\\" for row in rows)
    body.extend(["\\bottomrule", "\\end{tabular}"])
    return "\n".join(body) + "\n"


def table_from_csv(
    path: str | Path,
    *,
    columns: Sequence[str],
    headers: Sequence[str],
    aligns: str,
    formats: Sequence[str],
) -> str:
    """Render a whole result CSV as a table, in the column order given."""
    if not len(columns) == len(headers) == len(formats):
        raise ValueError("columns, headers and formats must line up")
    with open(path, encoding="utf-8", newline="") as handle:
        rows = [
            [format_value(row[c], f) for c, f in zip(columns, formats)]
            for row in csv.DictReader(handle)
        ]
    return render_table(headers=list(headers), aligns=aligns, rows=rows)


def write_generated(body: str, path: str | Path) -> None:
    """Write a generated file, stamped so nobody edits it by hand."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_HEADER + body, encoding="utf-8")


#: E5, passage localisation. Still the only evaluation whose CSV schema exists;
#: the recognition and correction registries are added when those evaluations
#: produce their first CSV.
#:
#: Per cohort, never pooled. The gate was pre-registered on the workbook batch
#: when it was all that existed, so scoring the two together would be moving the
#: test set after seeing the numbers. `docs/notes/2026-09-21-e5-localisation.md`
#: has the reasoning.
COHORTS: tuple[str, ...] = ("catalogue", "workbook")


def _localisation_macros(cohort: str) -> tuple[Macro, ...]:
    """The certain-band figures for one cohort, counts and their rates.

    Each rate names its own denominator, because the three the report needs are
    different: pieces in the cohort, certain pieces for a Livre figure, and
    pieces with a recoverable printed chapter number for a chapter figure.
    """
    summary = f"localisation-summary-{cohort}.csv"
    certain = {"confidence": "certain"}
    suffix = cohort.capitalize()
    return (
        Macro(f"locPieces{suffix}", summary, certain, "total", "int"),
        Macro(f"locLocated{suffix}", summary, certain, "located", "int"),
        Macro(f"locLivreCorrect{suffix}", summary, certain, "livre_correct", "int"),
        Macro(
            f"locLivreAccuracy{suffix}", summary, certain,
            "livre_correct", "pct1", over="total",
        ),
        Macro(
            f"locChapterScoreable{suffix}", summary, certain,
            "chapter_scoreable", "int",
        ),
        Macro(
            f"locChapterCorrect{suffix}", summary, certain,
            "chapter_correct", "int",
        ),
        Macro(
            f"locChapterAccuracy{suffix}", summary, certain,
            "chapter_correct", "pct1", over="chapter_scoreable",
        ),
        Macro(
            f"locChapterUnavailable{suffix}", summary, certain,
            "chapter_unavailable", "int",
        ),
        # The third state, and the reason the other two do not sum to the
        # cohort: the editor catalogued the piece to a Livre and named no
        # chapter, so there is no reference to score against. Without it the
        # report says "125 of 317 because 191 print no number", which accounts
        # for 316.
        Macro(
            f"locChapterUnreferenced{suffix}", summary, certain,
            "chapter_unreferenced", "int",
        ),
    )


LOCALISATION_MACROS: tuple[Macro, ...] = tuple(
    macro for cohort in COHORTS for macro in _localisation_macros(cohort)
)


#: E6, throughput and structural quality. Descriptive only: these are the
#: harness's own counts and timings, not a measurement against a reference, so
#: no macro here is an accuracy.
#:
#: Structure is family A alone. Books 13 to 24 print no table of contents, so
#: there is nothing to calibrate against and `structure.csv` has no row for
#: them. A macro named for the whole corpus would put family A's figure behind
#: the whole corpus's denominator.
THROUGHPUT_MACROS: tuple[Macro, ...] = (
    Macro("ocrBooks", "throughput.csv", {"cohort": "all"}, "books", "int"),
    Macro("ocrPages", "throughput.csv", {"cohort": "all"}, "pages", "int"),
    Macro("ocrPagesFailed", "throughput.csv", {"cohort": "all"}, "failed", "int"),
    Macro("ocrHours", "throughput.csv", {"cohort": "all"}, "seconds", "hours2"),
    Macro(
        "ocrSecondsPerPage", "throughput.csv", {"cohort": "all"},
        "seconds_per_page", "num3",
    ),
    Macro("ocrPassages", "throughput.csv", {"cohort": "all"}, "passages", "int"),
    Macro("ocrBooksFamilyA", "throughput.csv", {"cohort": "A"}, "books", "int"),
    Macro("ocrBooksFamilyB", "throughput.csv", {"cohort": "B"}, "books", "int"),
    Macro("ocrPagesFamilyA", "throughput.csv", {"cohort": "A"}, "pages", "int"),
    Macro("ocrPagesFamilyB", "throughput.csv", {"cohort": "B"}, "pages", "int"),
    Macro(
        "ocrSecondsPerPageFamilyA", "throughput.csv", {"cohort": "A"},
        "seconds_per_page", "num3",
    ),
    Macro(
        "ocrSecondsPerPageFamilyB", "throughput.csv", {"cohort": "B"},
        "seconds_per_page", "num3",
    ),
    Macro("structBooksA", "structure.csv", {"cohort": "A"}, "books", "int"),
    Macro("structChaptersA", "structure.csv", {"cohort": "A"}, "toc_chapters", "int"),
    Macro("structMatchedA", "structure.csv", {"cohort": "A"}, "matched", "int"),
    Macro("structMissingA", "structure.csv", {"cohort": "A"}, "missing", "int"),
    Macro("structSpuriousA", "structure.csv", {"cohort": "A"}, "spurious", "int"),
    # Named for what they measure. The detector's chapter decisions were
    # hand-corrected before calibration ran, 128 promotions and 217
    # demotions over family A, so these are not the detector unaided and a
    # sentence citing them cannot say they are without the macro name
    # contradicting it. docs/notes/2026-09-22-structural-figures-are-hand-checked.md
    Macro(
        "structRecallHandCheckedA", "structure.csv", {"cohort": "A"},
        "recall", "pct1",
    ),
    Macro(
        "structPrecisionHandCheckedA", "structure.csv", {"cohort": "A"},
        "precision", "pct1",
    ),
)


#: Section 3, the corpus. Descriptive, and counted from the repository's own
#: files rather than from the production database, so what has no macro here is
#: what this repository cannot derive: `src/amadis_htr/corpus.py` names the
#: three figures the design spec states in prose and this registry drops.
#:
#: The cohorts partition the aligned pieces and not the reference, so
#: `\corpusPieces` is larger than the two cohort counts together and
#: `\corpusUnaligned` is the difference.
CORPUS_MACROS: tuple[Macro, ...] = (
    Macro("corpusPieces", "corpus.csv", {"cohort": "all"}, "pieces", "int"),
    Macro("corpusAligned", "corpus.csv", {"cohort": "all"}, "aligned", "int"),
    Macro("corpusUnaligned", "corpus.csv", {"cohort": "all"}, "unaligned", "int"),
    Macro("corpusLivres", "corpus.csv", {"cohort": "all"}, "livres", "int"),
    Macro("corpusCertain", "corpus.csv", {"cohort": "all"}, "certain", "int"),
    Macro(
        "corpusCertainShare", "corpus.csv", {"cohort": "all"},
        "certain", "pct1", over="pieces",
    ),
    Macro("corpusConjecture", "corpus.csv", {"cohort": "all"}, "conjecture", "int"),
    Macro("corpusUncertain", "corpus.csv", {"cohort": "all"}, "uncertain", "int"),
    Macro("corpusUnassigned", "corpus.csv", {"cohort": "all"}, "none", "int"),
    # The extract length is what survives of the design spec's "1411 code
    # points on average": the alignment export carries both offsets, so the
    # span a piece occupies in the baseline text is derivable even though the
    # baseline text itself is not in this repository.
    Macro("corpusCharsMean", "corpus.csv", {"cohort": "all"}, "chars_mean", "num0"),
    Macro(
        "corpusCharsMedian", "corpus.csv", {"cohort": "all"}, "chars_median", "num0"
    ),
    Macro("corpusCharsMin", "corpus.csv", {"cohort": "all"}, "chars_min", "int"),
    Macro("corpusCharsMax", "corpus.csv", {"cohort": "all"}, "chars_max", "int"),
    Macro(
        "corpusPiecesCatalogue", "corpus.csv", {"cohort": "catalogue"},
        "pieces", "int",
    ),
    Macro(
        "corpusPiecesWorkbook", "corpus.csv", {"cohort": "workbook"}, "pieces", "int"
    ),
    Macro(
        "corpusCharsMeanCatalogue", "corpus.csv", {"cohort": "catalogue"},
        "chars_mean", "num0",
    ),
    Macro(
        "corpusCharsMeanWorkbook", "corpus.csv", {"cohort": "workbook"},
        "chars_mean", "num0",
    ),
    Macro("trainPages", "training.csv", {"split": "all"}, "pages", "int"),
    Macro("trainPagesTrain", "training.csv", {"split": "train"}, "pages", "int"),
    Macro("trainPagesVal", "training.csv", {"split": "val"}, "pages", "int"),
    Macro("trainCollections", "training.csv", {"split": "all"}, "collections", "int"),
)


#: E2, the marker-anchor accept rule.
#:
#: Two denominators that may not be swapped. The `corrReach*` macros count what
#: the pass would look at over all 24 books, a deterministic property of the
#: recognition output with no model in it. The rest count what happened on the
#: 400 sampled pages that were offered to the model. A rate over one may not be
#: printed against the other, which is why the prefixes differ.
#:
#: `corrRewritesCaught` is the one figure that speaks to C2: the rule refusing
#: a reply that edited text outside the markers. The protocol failures beside
#: it are replies that never became candidate edits, and pooling the two would
#: let a flaky JSON parser inflate the headline.
CORRECTION_MACROS: tuple[Macro, ...] = (
    Macro("corrReachPages", "correction-reach.csv", {"cohort": "all"}, "pages", "int"),
    Macro(
        "corrReachPagesWithSpan", "correction-reach.csv", {"cohort": "all"},
        "pages_with_span", "int",
    ),
    Macro(
        "corrReachPageShare", "correction-reach.csv", {"cohort": "all"},
        "pages_with_span", "pct1", over="pages",
    ),
    Macro(
        "corrReachCorrectable", "correction-reach.csv", {"cohort": "all"},
        "correctable", "int",
    ),
    Macro(
        "corrReachLinesWithSpan", "correction-reach.csv", {"cohort": "all"},
        "lines_with_span", "int",
    ),
    Macro(
        "corrReachLineShare", "correction-reach.csv", {"cohort": "all"},
        "lines_with_span", "pct1", over="correctable",
    ),
    Macro("corrReachSpans", "correction-reach.csv", {"cohort": "all"}, "spans", "int"),
    Macro(
        "corrPages", "correction-verdicts.csv", {"cohort": "all"}, "pages", "int"
    ),
    Macro(
        "corrOffered", "correction-verdicts.csv", {"cohort": "all"}, "offered", "int"
    ),
    Macro(
        "corrSpansOffered", "correction-verdicts.csv", {"cohort": "all"},
        "spans_offered", "int",
    ),
    Macro(
        "corrAccepted", "correction-verdicts.csv", {"cohort": "all"}, "accepted", "int"
    ),
    # Read from the interval file, never from the pooled counts: the draw is
    # equal per family and the frame is not, so accepted/offered over the
    # sample would weight family A at more than twice its share of the corpus.
    Macro(
        "corrAcceptRate", "correction-interval.csv",
        {"cohort": "corpus", "measure": "accept"}, "point", "pct1",
    ),
    Macro(
        "corrRejected", "correction-verdicts.csv", {"cohort": "all"}, "rejected", "int"
    ),

    Macro(
        "corrRewritesCaught", "correction-verdicts.csv", {"cohort": "all"},
        "rewrites_caught", "int",
    ),
    Macro(
        "corrRewriteRate", "correction-interval.csv",
        {"cohort": "corpus", "measure": "rewrite"}, "point", "pct1",
    ),
    Macro(
        "corrProtocolFailures", "correction-verdicts.csv", {"cohort": "all"},
        "protocol_failures", "int",
    ),
    Macro(
        "corrChangedSpans", "correction-verdicts.csv", {"cohort": "all"},
        "changed_spans", "int",
    ),
    Macro(
        "corrAcceptedUnchanged", "correction-verdicts.csv", {"cohort": "all"},
        "accepted_unchanged", "int",
    ),
    # The size of what was refused, so "rewrites caught" is a defensible
    # number rather than a bucket that a moved space also falls into.
    Macro(
        "corrRewriteEdits", "correction-verdicts.csv", {"cohort": "all"},
        "rewrite_edits", "int",
    ),
    Macro(
        "corrRewriteSegments", "correction-verdicts.csv", {"cohort": "all"},
        "rewrite_segments", "int",
    ),
    Macro(
        "corrRewritesSubstantial", "correction-verdicts.csv", {"cohort": "all"},
        "rewrites_substantial", "int",
    ),
    # How much of the sample sat on the span-locating fallback that can mark
    # one word twice. E2 cannot fix that hole; it can bound it.
    Macro(
        "corrOnFindFallback", "correction-verdicts.csv", {"cohort": "all"},
        "on_find_fallback", "int",
    ),
    Macro(
        "corrFindFallbackShare", "correction-verdicts.csv", {"cohort": "all"},
        "on_find_fallback", "pct1", over="offered",
    ),
    Macro(
        "corrAcceptLow", "correction-interval.csv",
        {"cohort": "corpus", "measure": "accept"}, "low", "pct1",
    ),
    Macro(
        "corrAcceptHigh", "correction-interval.csv",
        {"cohort": "corpus", "measure": "accept"}, "high", "pct1",
    ),
    Macro(
        "corrOfferedFamilyA", "correction-verdicts.csv", {"cohort": "A"},
        "offered", "int",
    ),
    Macro(
        "corrOfferedFamilyB", "correction-verdicts.csv", {"cohort": "B"},
        "offered", "int",
    ),
    Macro(
        "corrAcceptRateFamilyA", "correction-interval.csv",
        {"cohort": "A", "measure": "accept"}, "point", "pct1",
    ),
    Macro(
        "corrAcceptRateFamilyB", "correction-interval.csv",
        {"cohort": "B", "measure": "accept"}, "point", "pct1",
    ),
)


#: Every registry with a measured CSV behind it, in the order they reach the
#: page. `eval/render_macros.py` renders exactly this and the suite asserts the
#: committed `macros.tex` matches, so a registry added here without rerunning
#: the pipeline fails the suite rather than going unnoticed.
REGISTRIES: tuple[tuple[Macro, ...], ...] = (
    CORPUS_MACROS,
    LOCALISATION_MACROS,
    THROUGHPUT_MACROS,
    CORRECTION_MACROS,
)

#: Flattened, which is what a renderer wants.
ALL_MACROS: tuple[Macro, ...] = tuple(
    macro for registry in REGISTRIES for macro in registry
)
