"""`eval/results/*.csv` into the LaTeX the report reads.

Rule 1 of the repository architecture: no number in the report is typed by
hand. Every figure in the prose is a macro defined here and every table is an
`\\input` of a file written here, both from the evaluation's own CSV output.

The rule holds because an undefined control sequence stops a LaTeX build. A
figure that has not been measured therefore has no macro, and citing it fails
the build instead of reaching the page. `\\newcommand` and not
`\\providecommand` or `\\def`, so a name collision fails the same way rather
than silently keeping one of the two definitions.

Rounding lives in `format_value` and nowhere else, so a number cannot be
reported to three decimals in the text and two in a table.

Only the localisation results have a schema today. The recognition and
correction registries are added when those evaluations produce their first
CSV, because a registry written ahead of the data is a guess about the data.
"""

import csv
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Mapping, Sequence

_LETTERS_ONLY = re.compile(r"[A-Za-z]+")

_ESCAPES = {
    "\\": "\\textbackslash{}",
    "&": "\\&",
    "%": "\\%",
    "$": "\\$",
    "#": "\\#",
    "_": "\\_",
    "{": "\\{",
    "}": "\\}",
    "~": "\\textasciitilde{}",
    "^": "\\textasciicircum{}",
}

_HEADER = (
    "% Generated by src/amadis_htr/report_macros.py from eval/results/*.csv.\n"
    "% Do not edit: rerun eval/run_all.sh instead.\n"
    "%\n"
    "% Empty until the evaluation that feeds it runs. Citing a figure before it\n"
    "% is measured is an undefined control sequence, which stops the build.\n"
    "% That is the point.\n"
)


class MacroNameError(ValueError):
    """Raised when a macro name is not a legal TeX control sequence."""


@dataclass(frozen=True)
class Macro:
    """One reported figure: where it is read from and how it is rounded.

    `over` names a second column on the same row, and the figure becomes the
    ratio of the two. The results CSVs hold counts, never rates, because a
    count is what the evaluation observed and a rate is a reading of it that
    depends on which denominator is meant. Declaring the denominator here
    keeps both on the page from one measurement: the report says 315 of 317
    and 99.4% without either being typed.
    """

    name: str
    csv: str
    select: Mapping[str, str] = field(default_factory=dict)
    column: str = ""
    fmt: str = "text"
    over: str = ""


def escape(text: str) -> str:
    """Make a string safe to typeset, so a printed title cannot run LaTeX."""
    return "".join(_ESCAPES.get(c, c) for c in text)


def format_value(raw: str, fmt: str) -> str:
    """Render one CSV cell. Every rounding decision in the report is here.

    A percentage that rounds to zero is written `<0.01\\%` rather than
    `0.00\\%`, because a measured non-zero error rate is not a perfect result
    and the report must not claim one.
    """
    if fmt == "text":
        return escape(raw)
    if fmt == "int":
        return f"{int(float(raw)):d}"
    if fmt.startswith("num"):
        return f"{float(raw):.{int(fmt[3:])}f}"
    if fmt.startswith("pct"):
        places = int(fmt[3:])
        value = float(raw) * 100
        floor = 10.0**-places
        if 0 < value < floor:
            return f"<{floor:.{places}f}\\%"
        return f"{value:.{places}f}\\%"
    raise ValueError(f"unknown format {fmt!r}")


def _check_name(name: str) -> None:
    if not _LETTERS_ONLY.fullmatch(name):
        raise MacroNameError(
            f"{name!r} is not a legal control sequence name. TeX stops a control "
            "sequence at the first non-letter, so a digit or an underscore would "
            "put the rest of the name on the page instead of raising an error."
        )


def _select(path: Path, criteria: Mapping[str, str]) -> dict[str, str]:
    with open(path, encoding="utf-8", newline="") as handle:
        rows = [
            row
            for row in csv.DictReader(handle)
            if all(row[key] == value for key, value in criteria.items())
        ]
    if not rows:
        raise KeyError(
            f"{path.name}: no row matches {criteria!r}. The evaluation that "
            "writes this file did not produce the band the report cites."
        )
    if len(rows) > 1:
        raise ValueError(
            f"{path.name}: {criteria!r} matches {len(rows)} rows. A macro names "
            "one figure, so the selector has to identify one row."
        )
    return rows[0]


def render_macros(macros: Iterable[Macro], results: str | Path) -> str:
    """Render one `\\newcommand` per reported figure."""
    results = Path(results)
    lines: list[str] = []
    seen: set[str] = set()
    for macro in macros:
        _check_name(macro.name)
        if macro.name in seen:
            raise MacroNameError(f"{macro.name!r} is defined twice")
        seen.add(macro.name)
        row = _select(results / macro.csv, macro.select)
        if macro.over:
            denominator = float(row[macro.over])
            if denominator == 0:
                raise ValueError(
                    f"{macro.name}: {macro.over} is zero on the selected row, so "
                    "the rate does not exist. A band with nothing in it has no "
                    "accuracy, and reporting one would invent a denominator."
                )
            raw = str(float(row[macro.column]) / denominator)
        else:
            raw = row[macro.column]
        value = format_value(raw, macro.fmt)
        lines.append(f"\\newcommand{{\\{macro.name}}}{{{value}}}")
    return "\n".join(lines) + "\n"


def render_table(
    *, headers: Sequence[str], aligns: str, rows: Sequence[Sequence[str]]
) -> str:
    """Render a `booktabs` tabular body, cells already formatted.

    No vertical rules and no `\\hline`, which is what `booktabs` is for. The
    caller wraps this in whatever float and caption the report wants, so the
    same table can be a figure in the report and a slide in the deck.
    """
    if len(aligns) != len(headers):
        raise ValueError(
            f"{len(headers)} headers against {len(aligns)} alignment letters"
        )
    for row in rows:
        if len(row) != len(headers):
            raise ValueError(
                f"a row has {len(row)} cells but the table has "
                f"{len(headers)} columns"
            )
    body = [
        f"\\begin{{tabular}}{{{aligns}}}",
        "\\toprule",
        " & ".join(headers) + " \\\\",
        "\\midrule",
    ]
    body.extend(" & ".join(row) + " \\\\" for row in rows)
    body.extend(["\\bottomrule", "\\end{tabular}"])
    return "\n".join(body) + "\n"


def table_from_csv(
    path: str | Path,
    *,
    columns: Sequence[str],
    headers: Sequence[str],
    aligns: str,
    formats: Sequence[str],
) -> str:
    """Render a whole result CSV as a table, in the column order given."""
    if not len(columns) == len(headers) == len(formats):
        raise ValueError("columns, headers and formats must line up")
    with open(path, encoding="utf-8", newline="") as handle:
        rows = [
            [format_value(row[c], f) for c, f in zip(columns, formats)]
            for row in csv.DictReader(handle)
        ]
    return render_table(headers=list(headers), aligns=aligns, rows=rows)


def write_generated(body: str, path: str | Path) -> None:
    """Write a generated file, stamped so nobody edits it by hand."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_HEADER + body, encoding="utf-8")


#: E5, passage localisation. Still the only evaluation whose CSV schema exists;
#: the recognition and correction registries are added when those evaluations
#: produce their first CSV.
#:
#: Per cohort, never pooled. The gate was pre-registered on the workbook batch
#: when it was all that existed, so scoring the two together would be moving the
#: test set after seeing the numbers. `docs/notes/2026-09-21-e5-localisation.md`
#: has the reasoning.
COHORTS: tuple[str, ...] = ("catalogue", "workbook")


def _localisation_macros(cohort: str) -> tuple[Macro, ...]:
    """The certain-band figures for one cohort, counts and their rates.

    Each rate names its own denominator, because the three the report needs are
    different: pieces in the cohort, certain pieces for a Livre figure, and
    pieces with a recoverable printed chapter number for a chapter figure.
    """
    summary = f"localisation-summary-{cohort}.csv"
    certain = {"confidence": "certain"}
    suffix = cohort.capitalize()
    return (
        Macro(f"locPieces{suffix}", summary, certain, "total", "int"),
        Macro(f"locLocated{suffix}", summary, certain, "located", "int"),
        Macro(f"locLivreCorrect{suffix}", summary, certain, "livre_correct", "int"),
        Macro(
            f"locLivreAccuracy{suffix}", summary, certain,
            "livre_correct", "pct1", over="total",
        ),
        Macro(
            f"locChapterScoreable{suffix}", summary, certain,
            "chapter_scoreable", "int",
        ),
        Macro(
            f"locChapterCorrect{suffix}", summary, certain,
            "chapter_correct", "int",
        ),
        Macro(
            f"locChapterAccuracy{suffix}", summary, certain,
            "chapter_correct", "pct1", over="chapter_scoreable",
        ),
        Macro(
            f"locChapterUnavailable{suffix}", summary, certain,
            "chapter_unavailable", "int",
        ),
    )


LOCALISATION_MACROS: tuple[Macro, ...] = tuple(
    macro for cohort in COHORTS for macro in _localisation_macros(cohort)
)
