import re
from pathlib import Path

import pytest

from amadis_htr.report_macros import (
    ALL_MACROS,
    LOCALISATION_MACROS,
    Macro,
    MacroNameError,
    escape,
    format_value,
    render_macros,
    render_table,
    table_from_csv,
    write_generated,
)

REPO = Path(__file__).resolve().parent.parent


def _results(tmp_path):
    path = tmp_path / "localisation-summary.csv"
    path.write_text(
        "confidence,total,located,livre_correct,chapter_scoreable,chapter_correct\n"
        "certain,400,380,370,300,290\n"
        "conjecture,40,30,25,20,18\n",
        encoding="utf-8",
    )
    return tmp_path


def test_a_macro_name_may_only_hold_letters():
    # TeX control sequences stop at the first non-letter, so \locCer1 is \locCer
    # followed by a stray 1 on the page rather than an error.
    with pytest.raises(MacroNameError):
        render_macros([Macro("locCer1", "x.csv", {}, "c", "num3")], ".")
    with pytest.raises(MacroNameError):
        render_macros([Macro("loc_cer", "x.csv", {}, "c", "num3")], ".")


def test_a_macro_is_newcommand_so_a_duplicate_fails_the_build(tmp_path):
    # \providecommand would silently keep the first definition and \def the
    # last. Both hide a name collision that changes a reported number.
    out = render_macros(
        [Macro("locTotalCertain", "localisation-summary.csv", {"confidence": "certain"}, "total", "int")],
        _results(tmp_path),
    )
    assert "\\newcommand{\\locTotalCertain}{400}" in out


def test_a_selector_that_matches_no_row_is_an_error_not_an_empty_macro(tmp_path):
    with pytest.raises(KeyError, match="confidence"):
        render_macros(
            [Macro("locTotalMissing", "localisation-summary.csv", {"confidence": "absent"}, "total", "int")],
            _results(tmp_path),
        )


def test_a_selector_matching_several_rows_is_an_error(tmp_path):
    with pytest.raises(ValueError, match="2 rows"):
        render_macros(
            [Macro("locTotalAny", "localisation-summary.csv", {}, "total", "int")],
            _results(tmp_path),
        )


def test_rounding_lives_in_one_place():
    assert format_value("0.0049812", "pct2") == "0.50\\%"
    assert format_value("0.9504", "num3") == "0.950"
    assert format_value("380", "int") == "380"
    # Grouped above a thousand: 14111 on the page is a string of digits.
    assert format_value("14111", "int") == "14,111"
    assert format_value("0.5", "pct1") == "50.0\\%"


def test_the_french_report_gets_french_number_typography():
    # A French reader parses 14,111 as fourteen and a bit, so grouping is a
    # thin space and the decimal mark is a comma. The percent sign takes a
    # thin space too, as French typography sets it.
    assert format_value("14111", "int", "fr") == "14\\,111"
    assert format_value("0.9504", "num3", "fr") == "0,950"
    assert format_value("20340", "hours2", "fr") == "5,65"
    assert format_value("0.5", "pct1", "fr") == "50,0\\,\\%"
    assert format_value("0.00004", "pct2", "fr") == "<0,01\\,\\%"


def test_a_fraction_that_rounds_to_zero_percent_is_not_claimed_as_zero():
    # A CER of 0.00004 is not "0.00%". Reporting it as zero would claim a
    # perfect transcription the measurement does not support.
    assert format_value("0.00004", "pct2") == "<0.01\\%"


def test_text_is_escaped_so_a_title_cannot_run_latex():
    assert escape("Amadis & Oriane, 50% of #3_a") == "Amadis \\& Oriane, 50\\% of \\#3\\_a"


def test_a_table_is_booktabs_with_no_vertical_rules():
    body = render_table(
        headers=["Confidence", "Total"],
        aligns="lr",
        rows=[["certain", "400"], ["conjecture", "40"]],
    )
    assert "\\toprule" in body and "\\midrule" in body and "\\bottomrule" in body
    assert "|" not in body
    assert "certain & 400 \\\\" in body


def test_a_table_row_count_must_match_the_header_count():
    with pytest.raises(ValueError, match="2 columns"):
        render_table(headers=["a", "b"], aligns="ll", rows=[["one"]])


def test_a_table_from_csv_takes_its_columns_in_the_order_given(tmp_path):
    body = table_from_csv(
        _results(tmp_path) / "localisation-summary.csv",
        columns=["located", "confidence"],
        headers=["Located", "Band"],
        aligns="rl",
        formats=["int", "text"],
    )
    assert "380 & certain \\\\" in body
    assert "Located & Band" in body


def test_generated_files_say_they_are_generated(tmp_path):
    out = tmp_path / "generated" / "macros.tex"
    write_generated("\\newcommand{\\x}{1}\n", out)
    text = out.read_text(encoding="utf-8")
    assert text.startswith("% Generated by")
    assert "do not edit" in text.lower()
    assert "\\newcommand{\\x}{1}" in text


def test_the_committed_macros_file_is_what_the_writer_emits(tmp_path):
    # report/generated/ is committed so the report builds from a fresh clone,
    # and the README calls every file in it generated. Rule 1 says no number in
    # the report is typed by hand, which is only true while the committed file
    # is exactly what the registry renders from the committed results. Editing
    # either by hand fails here instead of reaching the page.
    reference = tmp_path / "macros.tex"
    write_generated(render_macros(ALL_MACROS, REPO / "eval/results"), reference)
    committed = REPO / "report" / "generated" / "macros.tex"
    assert committed.read_text(encoding="utf-8") == reference.read_text(
        encoding="utf-8"
    )


def test_the_committed_french_macros_file_is_what_the_writer_emits(tmp_path):
    reference = tmp_path / "macros.tex"
    write_generated(
        render_macros(ALL_MACROS, REPO / "eval/results", "fr"), reference
    )
    committed = REPO / "report" / "generated" / "fr" / "macros.tex"
    assert committed.read_text(encoding="utf-8") == reference.read_text(
        encoding="utf-8"
    )


def test_every_figure_the_e5_note_states_comes_out_of_the_registry():
    # The note's prose quotes 99.4% and 76.8% for the gated cohort and 99.0%
    # and 73.1% for the other. Those four are the whole E5 result, and they are
    # exactly the kind of number that drifts once it is written in two places.
    rendered = render_macros(LOCALISATION_MACROS, REPO / "eval/results")
    for name, value in [
        ("locPiecesWorkbook", "317"),
        ("locLivreCorrectWorkbook", "315"),
        ("locLivreAccuracyWorkbook", "99.4\\%"),
        ("locChapterCorrectWorkbook", "96"),
        ("locChapterScoreableWorkbook", "125"),
        ("locChapterAccuracyWorkbook", "76.8\\%"),
        ("locPiecesCatalogue", "101"),
        ("locLivreAccuracyCatalogue", "99.0\\%"),
        ("locChapterAccuracyCatalogue", "73.1\\%"),
    ]:
        assert f"\\newcommand{{\\{name}}}{{{value}}}" in rendered


def test_a_rate_over_an_empty_band_is_an_error_not_a_zero(tmp_path):
    # The workbook cohort has no conjecture pieces at all. A rate there is 0/0,
    # and rendering it as 0.0% would report a failure the evaluation never
    # observed.
    path = tmp_path / "localisation-summary-workbook.csv"
    path.write_text(
        "confidence,total,livre_correct\nconjecture,0,0\n", encoding="utf-8"
    )
    macro = Macro(
        "locLivreAccuracyWorkbook",
        "localisation-summary-workbook.csv",
        {"confidence": "conjecture"},
        "livre_correct",
        "pct1",
        over="total",
    )
    with pytest.raises(ValueError, match="does not exist"):
        render_macros([macro], tmp_path)


def test_every_figure_the_report_cites_is_a_macro_the_registry_defines():
    # Rule 1's enforcement is an undefined control sequence, which only bites
    # when Tectonic runs. That job is slow and needs a LaTeX toolchain, so the
    # same breakage is caught here in the fast suite: a section citing a figure
    # the evaluation has not produced fails before anyone builds a PDF.
    #
    # The registry is the vocabulary. Anything else a section uses is either a
    # LaTeX control sequence or a macro from the preamble, so both are read and
    # the difference is what has nothing behind it.
    defined = {macro.name for macro in ALL_MACROS}
    preamble = (REPO / "report/preamble.tex").read_text(encoding="utf-8")
    defined |= set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", preamble))
    generated = set(
        re.findall(
            r"\\newcommand\{\\([A-Za-z]+)\}",
            (REPO / "report/generated/macros.tex").read_text(encoding="utf-8"),
        )
    )
    assert generated == {macro.name for macro in ALL_MACROS}

    sections = [
        *sorted((REPO / "report/sections").glob("*.tex")),
        *sorted((REPO / "report/sections-fr").glob("*.tex")),
    ]
    for section in sections:
        body = "\n".join(
            line for line in section.read_text(encoding="utf-8").splitlines()
            if not line.lstrip().startswith("%")
        )
        cited = set(re.findall(r"\\([a-z][A-Za-z]*)", body))
        # A figure's name is the registry's own naming convention: a lowercase
        # head followed by a capital. Plain LaTeX commands (\section, \emph,
        # \ref) have no capital in them, so they do not reach this filter.
        figures = {name for name in cited if any(c.isupper() for c in name)}
        missing = sorted(figures - defined)
        assert not missing, (
            f"{section.name} cites {missing}, which no registry defines. "
            "Either the evaluation behind it has not run, or the name is wrong."
        )
